"""
Quality Assurance
=================

Simple example.

Example on how to run the quality assurance pre-processing using BrainPrep.
See :ref:`user guide <quality_assurance>` for details.

Data
----

Let's first get some anatomical data.
"""

from pathlib import Path
from brainprep.datasets import IBCDataset
from brainprep.utils import Bunch

datadir = Path("/tmp/brainprep-data")
datadir.mkdir(parents=True, exist_ok=True)
dataset = IBCDataset(datadir)
data = Bunch(
    sub01=dataset.fetch(
        subject="01",
        modality="anat|dwi|func",
    ),
    sub02=dataset.fetch(
        subject="02",
        modality="anat|dwi|func",
    ),
)
print(data)


# %%
# Analysis
# --------
# 
# Let's now perform the preprocessing using BrainPrep.
# As with many tutorials, we won't execute the code directly here.
# However, feel free to set the 'dryrun' configuration to False
# to actually run each step and generate results on disk.


from brainprep.workflow import (
    brainprep_quality_assurance,
    brainprep_group_quality_assurance,
)
from brainprep.config import Config
from brainprep.reporting import RSTReport

outdir = Path("/tmp/brainprep-qa")
outdir.mkdir(parents=True, exist_ok=True)
with Config(dryrun=True, verbose=True):
    for subject_data in data.values():
        report = RSTReport()
        brainprep_quality_assurance(
            image_files=[
                subject_data.anat,
                subject_data.func,
                subject_data.dwi
            ],
            output_dir=outdir,
            keep_intermediate=True,
        )
        print(report)
    report = RSTReport()
    brainprep_group_quality_assurance(
        modalities=["T1w", 'bold', 'dwi'],
        output_dir=outdir,
    )
    print(report)


# %%
# CLI
# ---
# 
# Let's now generate the same analysis using the CLI. The goal here is to
# translate the workflow calls into explicit shell commands.
# See :ref:`user guide <cli>` for details.

from pprint import pprint

commands = []
commands.append(
    [
        [
            "brainprep", "subject-level-qa",
            "--image-files",
            f"{subject_data.anat},{subject_data.func},{subject_data.dwi}",
            "--output-dir", str(outdir),
            "--keep-intermediate",
        ] for subject_data in data.values()
    ]
)
commands.append(
    [
        [
            "brainprep", "group-level-qa",
            "--modalities", f"T1w,bold,dwi",
            "--output-dir", str(outdir),
        ]
    ]
)
pprint(commands)


# %%
# Container
# ---------
# 
# Note that the commands generated by the CLI are not limited to being
# displayed for reference; they can also be executed directly within the
# workflow‑dedicated container. By running the commands inside the container,
# you benefit from a controlled runtime context where all necessary
# dependencies, libraries, and configuration files are already available.
# In practice, this means that once the CLI has produced the appropriate
# instructions, you can simply copy and run them inside the container to
# achieve the intended results. You can find the BrainPrep images on Docker
# Hub: `Neurospin Docker Hub <https://hub.docker.com/u/neurospin>`_.
