"""
VBM
===

Simple example.

Example on how to run the VBM pre-processing using BrainPrep.
See :ref:`user guide <vbm>` for details.

Data
----

Let's first get some anatomical data.
"""

from pathlib import Path
from brainprep.datasets import OpenMSDataset
from brainprep.utils import Bunch

datadir = Path("/tmp/brainprep-data")
datadir.mkdir(parents=True, exist_ok=True)
dataset = OpenMSDataset(datadir)
data = Bunch(
    sub01=dataset.fetch(
        subject="01",
        modality="T1w",
        dtype="longitudinal",
    ),
    sub02=dataset.fetch(
        subject="02",
        modality="T1w",
        dtype="longitudinal",
    ),
)
print(data)


# %%
# Analysis
# --------
# 
# Let's now perform the preprocessing using BrainPrep.
# As with many tutorials, we won't execute the code directly here.
# However, feel free to set the 'dryrun' configuration to False
# to actually run each step and generate results on disk.

import shutil
from brainprep.workflow import (
    brainprep_group_vbm,
    brainprep_longitudinal_vbm,
    brainprep_vbm,
)
from brainprep.config import Config
from brainprep.reporting import RSTReport

outdir = Path("/tmp/brainprep-vbm")
if outdir.is_dir():
    shutil.rmtree(outdir)
outdir.mkdir(parents=True, exist_ok=True)
with Config(dryrun=True, verbose=True):
    for subject_data in data.values():
        report = RSTReport()
        outputs = brainprep_vbm(
            t1_file=subject_data.anat1,
            output_dir=outdir,
        )
        # print(report)
    outputs = brainprep_longitudinal_vbm(
        t1_files=[data.sub01.anat1, data.sub01.anat2],
        model=1,
        output_dir=outdir,
    )
    outputs = brainprep_group_vbm(
        output_dir=outdir,
    )
    outputs = brainprep_group_vbm(
        output_dir=outdir,
        longitudinal=True,
    )


# %%
# CLI
# ---
# 
# Let's now generate the same analysis using the CLI. The goal here is to
# translate the workflow calls into explicit shell commands.
# See :ref:`user guide <cli>` for details.

from pprint import pprint

commands = []
commands.append(
    [
        [
            "brainprep", "subject-level-vbm",
            "--t1_file", str(subject_data.anat1),
            "--output-dir", str(outdir),
            "--keep-intermediate",
        ] for subject_data in data.values()
    ]
)
commands.append(
    [
        [
            "brainprep", "longitudinal-vbm",
            "--t1_files", f"{subject_data.anat1},{subject_data.anat2}",
            "--model", "1",
            "--output-dir", str(outdir),
            "--keep-intermediate",
        ] for subject_data in data.values()
    ]
)
commands.append(
    [
        [
            "brainprep", "group-level-vbm",
            "--output-dir", str(outdir),
        ],
        [
            "brainprep", "group-level-vbm",
            "--output-dir", str(outdir),
            "--longitudinal",
        ],
    ]
)
pprint(commands)


# %%
# Container
# ---------
# 
# Note that the commands generated by the CLI are not limited to being
# displayed for reference; they can also be executed directly within the
# workflow‑dedicated container. By running the commands inside the container,
# you benefit from a controlled runtime context where all necessary
# dependencies, libraries, and configuration files are already available.
# In practice, this means that once the CLI has produced the appropriate
# instructions, you can simply copy and run them inside the container to
# achieve the intended results. You can find the BrainPrep images on Docker
# Hub: `Neurospin Docker Hub <https://hub.docker.com/u/neurospin>`_.
